version: '3'
services:
  app:
    image: mircroservice
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/app'
      - '/node_modules'
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mircroservice
    volumes:
      - ./express-postgres/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
