version: '3'
services:
  app:
    image: docker-hapi-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/app'
      - '/node_modules'
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
