version: '3'
services:
  app:
    image: docker-express-hapi
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/app'
      - '/node_modules'
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: playground
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
